/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type AuthOtp = {
  _id: string
  _type: "authOtp"
  _createdAt: string
  _updatedAt: string
  _rev: string
  email?: string
  codeHash?: string
  expiresAt?: string
  attempts?: number
  createdAt?: string
}

export type Customer = {
  _id: string
  _type: "customer"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  email?: string
  phone?: string
  cpf?: string
  address?: {
    cep?: string
    street?: string
    number?: string
    complement?: string
    neighborhood?: string
    city?: string
    state?: string
  }
  createdAt?: string
  updatedAt?: string
  passwordHash?: string
}

export type ProductReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "product"
}

export type Order = {
  _id: string
  _type: "order"
  _createdAt: string
  _updatedAt: string
  _rev: string
  number?: string
  status?:
    | "aguardando_pagamento"
    | "pago"
    | "pago_conflito"
    | "enviado"
    | "entregue"
    | "expirado"
    | "cancelado"
  trackingCode?: string
  customer?: {
    name?: string
    email?: string
    phone?: string
    cpf?: string
  }
  address?: {
    cep?: string
    street?: string
    number?: string
    complement?: string
    neighborhood?: string
    city?: string
    state?: string
  }
  items?: Array<{
    product?: ProductReference
    title?: string
    price?: number
    _type: "orderItem"
    _key: string
  }>
  shipping?: {
    serviceId?: number
    company?: string
    name?: string
    price?: number
    deliveryDays?: number
    melhorEnvioOrderId?: string
    labelUrl?: string
  }
  subtotal?: number
  shippingTotal?: number
  total?: number
  conflictNote?: string
  payment?: {
    provider?: string
    checkoutUrl?: string
    expiresAt?: string
    captureMethod?: string
    installments?: number
    paidAmount?: number
    slug?: string
    transactionNsu?: string
    receiptUrl?: string
    paidAt?: string
  }
  processedEvents?: Array<string>
  accessToken?: string
  createdAt?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type CategoryReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "category"
}

export type Product = {
  _id: string
  _type: "product"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  }>
  price?: number
  compareAtPrice?: number
  badges?: Array<string>
  category?: CategoryReference
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h3" | "blockquote"
    listItem?: "bullet"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  details?: {
    material?: string
    dimensions?: string
    weight?: string
    glaze?: string
    careInstructions?: string
  }
  shipping?: {
    weightGrams?: number
    heightCm?: number
    widthCm?: number
    lengthCm?: number
  }
  sku?: string
  inventory?: number
  status?: "draft" | "active" | "archived"
  reservedUntil?: string
  reservedBy?: string
  soldAt?: string
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Category = {
  _id: string
  _type: "category"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | AuthOtp
  | Customer
  | ProductReference
  | Order
  | SanityImageAssetReference
  | CategoryReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: AVAILABLE_PRODUCTS_QUERY
// Query: *[_type == "product" && defined(slug.current) && status == "active" && inventory > 0] | order(_createdAt desc) {    _id,    title,    "slug": slug.current,    price,    badges,    inventory,    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),    "image": images[0],    "hoverImage": images[1]  }
export type AVAILABLE_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  badges: Array<string> | null
  inventory: number | null
  reserved: boolean | false | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
  hoverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: SOLD_PRODUCTS_QUERY
// Query: *[_type == "product" && status == "active" && defined(slug.current) && inventory == 0] | order(_updatedAt desc) [0...6] {    _id,    title,    "slug": slug.current,    price,    badges,    inventory,    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),    "image": images[0],    "hoverImage": images[1]  }
export type SOLD_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  badges: Array<string> | null
  inventory: number | null
  reserved: boolean | false | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
  hoverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: ALL_SOLD_PRODUCTS_QUERY
// Query: *[_type == "product" && status == "active" && defined(slug.current) && inventory == 0] | order(_updatedAt desc) {    _id,    title,    "slug": slug.current,    price,    badges,    inventory,    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),    "image": images[0],    "hoverImage": images[1]  }
export type ALL_SOLD_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  badges: Array<string> | null
  inventory: number | null
  reserved: boolean | false | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
  hoverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && status == "active" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    price,    compareAtPrice,    badges,    images,    "categoryId": category._ref,    description,    "plainDescription": pt::text(description),    details,    inventory,    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now())  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  compareAtPrice: number | null
  badges: Array<string> | null
  images: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  }> | null
  categoryId: string | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "blockquote" | "h3" | "normal"
    listItem?: "bullet"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }> | null
  plainDescription: string
  details: {
    material?: string
    dimensions?: string
    weight?: string
    glaze?: string
    careInstructions?: string
  } | null
  inventory: number | null
  reserved: boolean | false | null
} | null

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && defined(slug.current) && status == "active" && inventory > 0 && _id != $id] | score(category._ref == $categoryId) | order(_score desc, _createdAt desc) [0...3] {    _id,    title,    "slug": slug.current,    price,    badges,    inventory,    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),    "image": images[0],    "hoverImage": images[1]  }
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  badges: Array<string> | null
  inventory: number | null
  reserved: boolean | false | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
  hoverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: BAG_PRODUCTS_QUERY
// Query: *[_type == "product" && _id in $ids] {    _id,    title,    "slug": slug.current,    price,    "image": images[0],    "available": status == "active" && inventory > 0 && !(defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now())),    "reserved": status == "active" && inventory > 0 && defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),    shipping,    _rev  }
export type BAG_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
  available: boolean | false | null
  reserved: boolean | false | null
  shipping: {
    weightGrams?: number
    heightCm?: number
    widthCm?: number
    lengthCm?: number
  } | null
  _rev: string
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: ORDER_BY_ID_QUERY
// Query: *[_type == "order" && _id == $id][0] {   _id,  _rev,  number,  status,  trackingCode,  conflictNote,  accessToken,  customer,  address,  items[] { "productId": product._ref, title, price },  shipping,  subtotal,  shippingTotal,  total,  payment,  processedEvents,  createdAt }
export type ORDER_BY_ID_QUERY_RESULT = {
  _id: string
  _rev: string
  number: string | null
  status:
    | "aguardando_pagamento"
    | "cancelado"
    | "entregue"
    | "enviado"
    | "expirado"
    | "pago_conflito"
    | "pago"
    | null
  trackingCode: string | null
  conflictNote: string | null
  accessToken: string | null
  customer: {
    name?: string
    email?: string
    phone?: string
    cpf?: string
  } | null
  address: {
    cep?: string
    street?: string
    number?: string
    complement?: string
    neighborhood?: string
    city?: string
    state?: string
  } | null
  items: Array<{
    productId: string | null
    title: string | null
    price: number | null
  }> | null
  shipping: {
    serviceId?: number
    company?: string
    name?: string
    price?: number
    deliveryDays?: number
    melhorEnvioOrderId?: string
    labelUrl?: string
  } | null
  subtotal: number | null
  shippingTotal: number | null
  total: number | null
  payment: {
    provider?: string
    checkoutUrl?: string
    expiresAt?: string
    captureMethod?: string
    installments?: number
    paidAmount?: number
    slug?: string
    transactionNsu?: string
    receiptUrl?: string
    paidAt?: string
  } | null
  processedEvents: Array<string> | null
  createdAt: string | null
} | null

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: ORDERS_BY_CUSTOMER_EMAIL_QUERY
// Query: *[_type == "order" && lower(customer.email) == lower($email)] | order(createdAt desc) {      _id,  _rev,  number,  status,  trackingCode,  conflictNote,  accessToken,  customer,  address,  items[] { "productId": product._ref, title, price },  shipping,  subtotal,  shippingTotal,  total,  payment,  processedEvents,  createdAt  }
export type ORDERS_BY_CUSTOMER_EMAIL_QUERY_RESULT = Array<{
  _id: string
  _rev: string
  number: string | null
  status:
    | "aguardando_pagamento"
    | "cancelado"
    | "entregue"
    | "enviado"
    | "expirado"
    | "pago_conflito"
    | "pago"
    | null
  trackingCode: string | null
  conflictNote: string | null
  accessToken: string | null
  customer: {
    name?: string
    email?: string
    phone?: string
    cpf?: string
  } | null
  address: {
    cep?: string
    street?: string
    number?: string
    complement?: string
    neighborhood?: string
    city?: string
    state?: string
  } | null
  items: Array<{
    productId: string | null
    title: string | null
    price: number | null
  }> | null
  shipping: {
    serviceId?: number
    company?: string
    name?: string
    price?: number
    deliveryDays?: number
    melhorEnvioOrderId?: string
    labelUrl?: string
  } | null
  subtotal: number | null
  shippingTotal: number | null
  total: number | null
  payment: {
    provider?: string
    checkoutUrl?: string
    expiresAt?: string
    captureMethod?: string
    installments?: number
    paidAmount?: number
    slug?: string
    transactionNsu?: string
    receiptUrl?: string
    paidAt?: string
  } | null
  processedEvents: Array<string> | null
  createdAt: string | null
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: *[_type == "customer" && lower(email) == lower($email)][0] {    _id,    name,    email,    phone,    cpf,    address,    "hasPassword": defined(passwordHash),    createdAt,    updatedAt  }
export type CUSTOMER_BY_EMAIL_QUERY_RESULT = {
  _id: string
  name: string | null
  email: string | null
  phone: string | null
  cpf: string | null
  address: {
    cep?: string
    street?: string
    number?: string
    complement?: string
    neighborhood?: string
    city?: string
    state?: string
  } | null
  hasPassword: false | true
  createdAt: string | null
  updatedAt: string | null
} | null

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: CUSTOMER_BY_ID_QUERY
// Query: *[_type == "customer" && _id == $id][0] {    _id,    name,    email,    phone,    cpf,    address,    "hasPassword": defined(passwordHash),    createdAt,    updatedAt  }
export type CUSTOMER_BY_ID_QUERY_RESULT = {
  _id: string
  name: string | null
  email: string | null
  phone: string | null
  cpf: string | null
  address: {
    cep?: string
    street?: string
    number?: string
    complement?: string
    neighborhood?: string
    city?: string
    state?: string
  } | null
  hasPassword: false | true
  createdAt: string | null
  updatedAt: string | null
} | null

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: CUSTOMER_AUTH_BY_EMAIL_QUERY
// Query: *[_type == "customer" && lower(email) == lower($email)][0] {    _id,    name,    email,    passwordHash  }
export type CUSTOMER_AUTH_BY_EMAIL_QUERY_RESULT = {
  _id: string
  name: string | null
  email: string | null
  passwordHash: string | null
} | null

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: AUTH_OTP_BY_ID_QUERY
// Query: *[_type == "authOtp" && _id == $id][0] {    _id,    email,    codeHash,    expiresAt,    attempts  }
export type AUTH_OTP_BY_ID_QUERY_RESULT = {
  _id: string
  email: string | null
  codeHash: string | null
  expiresAt: string | null
  attempts: number | null
} | null

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "product" && defined(slug.current) && status == "active" && inventory > 0] | order(_createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    badges,\n    inventory,\n    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),\n    "image": images[0],\n    "hoverImage": images[1]\n  }\n': AVAILABLE_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && status == "active" && defined(slug.current) && inventory == 0] | order(_updatedAt desc) [0...6] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    badges,\n    inventory,\n    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),\n    "image": images[0],\n    "hoverImage": images[1]\n  }\n': SOLD_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && status == "active" && defined(slug.current) && inventory == 0] | order(_updatedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    badges,\n    inventory,\n    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),\n    "image": images[0],\n    "hoverImage": images[1]\n  }\n': ALL_SOLD_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && status == "active" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    compareAtPrice,\n    badges,\n    images,\n    "categoryId": category._ref,\n    description,\n    "plainDescription": pt::text(description),\n    details,\n    inventory,\n    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now())\n  }\n': PRODUCT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "product" && defined(slug.current) && status == "active" && inventory > 0 && _id != $id] | score(category._ref == $categoryId) | order(_score desc, _createdAt desc) [0...3] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    badges,\n    inventory,\n    "reserved": defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),\n    "image": images[0],\n    "hoverImage": images[1]\n  }\n': RELATED_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && _id in $ids] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    "image": images[0],\n    "available": status == "active" && inventory > 0 && !(defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now())),\n    "reserved": status == "active" && inventory > 0 && defined(reservedUntil) && dateTime(reservedUntil) > dateTime(now()),\n    shipping,\n    _rev\n  }\n': BAG_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "order" && _id == $id][0] { \n  _id,\n  _rev,\n  number,\n  status,\n  trackingCode,\n  conflictNote,\n  accessToken,\n  customer,\n  address,\n  items[] { "productId": product._ref, title, price },\n  shipping,\n  subtotal,\n  shippingTotal,\n  total,\n  payment,\n  processedEvents,\n  createdAt\n }\n': ORDER_BY_ID_QUERY_RESULT
    '\n  *[_type == "order" && lower(customer.email) == lower($email)] | order(createdAt desc) {\n    \n  _id,\n  _rev,\n  number,\n  status,\n  trackingCode,\n  conflictNote,\n  accessToken,\n  customer,\n  address,\n  items[] { "productId": product._ref, title, price },\n  shipping,\n  subtotal,\n  shippingTotal,\n  total,\n  payment,\n  processedEvents,\n  createdAt\n\n  }\n': ORDERS_BY_CUSTOMER_EMAIL_QUERY_RESULT
    '\n  *[_type == "customer" && lower(email) == lower($email)][0] {\n    _id,\n    name,\n    email,\n    phone,\n    cpf,\n    address,\n    "hasPassword": defined(passwordHash),\n    createdAt,\n    updatedAt\n  }\n': CUSTOMER_BY_EMAIL_QUERY_RESULT
    '\n  *[_type == "customer" && _id == $id][0] {\n    _id,\n    name,\n    email,\n    phone,\n    cpf,\n    address,\n    "hasPassword": defined(passwordHash),\n    createdAt,\n    updatedAt\n  }\n': CUSTOMER_BY_ID_QUERY_RESULT
    '\n  *[_type == "customer" && lower(email) == lower($email)][0] {\n    _id,\n    name,\n    email,\n    passwordHash\n  }\n': CUSTOMER_AUTH_BY_EMAIL_QUERY_RESULT
    '\n  *[_type == "authOtp" && _id == $id][0] {\n    _id,\n    email,\n    codeHash,\n    expiresAt,\n    attempts\n  }\n': AUTH_OTP_BY_ID_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
