/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type CategoryReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "category"
}

export type Product = {
  _id: string
  _type: "product"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  }>
  price?: number
  compareAtPrice?: number
  badges?: Array<string>
  category?: CategoryReference
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h3" | "blockquote"
    listItem?: "bullet"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  details?: {
    material?: string
    dimensions?: string
    weight?: string
    glaze?: string
    careInstructions?: string
  }
  sku?: string
  inventory?: number
  status?: "draft" | "active" | "archived"
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Category = {
  _id: string
  _type: "category"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CategoryReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: AVAILABLE_PRODUCTS_QUERY
// Query: *[_type == "product" && status == "active" && defined(slug.current) && inventory > 0] | order(_createdAt desc) {    _id,    title,    "slug": slug.current,    price,    badges,    inventory,    "image": images[0]  }
export type AVAILABLE_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  badges: Array<string> | null
  inventory: number | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: SOLD_PRODUCTS_QUERY
// Query: *[_type == "product" && status == "active" && defined(slug.current) && inventory == 0] | order(_updatedAt desc) [0...6] {    _id,    title,    "slug": slug.current,    price,    badges,    inventory,    "image": images[0]  }
export type SOLD_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  badges: Array<string> | null
  inventory: number | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
}>

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && status == "active" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    price,    compareAtPrice,    badges,    images,    "categoryId": category._ref,    description,    "plainDescription": pt::text(description),    details,    inventory  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  compareAtPrice: number | null
  badges: Array<string> | null
  images: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  }> | null
  categoryId: string | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "blockquote" | "h3" | "normal"
    listItem?: "bullet"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }> | null
  plainDescription: string
  details: {
    material?: string
    dimensions?: string
    weight?: string
    glaze?: string
    careInstructions?: string
  } | null
  inventory: number | null
} | null

// Source: ../apps/storefront/src/sanity/queries.ts
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[_type == "product" && status == "active" && defined(slug.current) && inventory > 0 && _id != $id] | score(category._ref == $categoryId) | order(_score desc, _createdAt desc) [0...3] {    _id,    title,    "slug": slug.current,    price,    badges,    inventory,    "image": images[0]  }
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string
  title: string | null
  slug: string | null
  price: number | null
  badges: Array<string> | null
  inventory: number | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  } | null
}>

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "product" && status == "active" && defined(slug.current) && inventory > 0] | order(_createdAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    badges,\n    inventory,\n    "image": images[0]\n  }\n': AVAILABLE_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && status == "active" && defined(slug.current) && inventory == 0] | order(_updatedAt desc) [0...6] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    badges,\n    inventory,\n    "image": images[0]\n  }\n': SOLD_PRODUCTS_QUERY_RESULT
    '\n  *[_type == "product" && status == "active" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    compareAtPrice,\n    badges,\n    images,\n    "categoryId": category._ref,\n    description,\n    "plainDescription": pt::text(description),\n    details,\n    inventory\n  }\n': PRODUCT_BY_SLUG_QUERY_RESULT
    '\n  *[_type == "product" && status == "active" && defined(slug.current) && inventory > 0 && _id != $id] | score(category._ref == $categoryId) | order(_score desc, _createdAt desc) [0...3] {\n    _id,\n    title,\n    "slug": slug.current,\n    price,\n    badges,\n    inventory,\n    "image": images[0]\n  }\n': RELATED_PRODUCTS_QUERY_RESULT
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
